### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jamesplease** [jamesplease/fi-calc#195]
Just jotting down some ideas for the next few things I want to add

- [ ] Fully test simulation-engine
- [ ] Support for bonds
  - [ ] Rebalance portfolio option
- [ ] Income/withdrawals that repeat
- [ ] Simba dataset
- [ ] SBBI dataset
