### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by jamesplease** [jamesplease/fi-calc#27]
- [x] Faster wake up times from Now's sleep (#26 )
- [x] Placeholder design elements ( #9 )
- [x] Larger screen designs ( #10 )

---

After this is done, I think I'd be happy sharing a link out for a first release.

**Comment by jamesplease** [comment]
Closing as done. I want to tidy up the large screen support a bit, as well as a few other things, but...I'm quite close!
