### ISSUE TITLE
Prerelease checklist

### ISSUE THREAD

**Issue by jamesplease** [jamesplease/fi-calc#36]
- [x] Update styling of large screen results
- [x] Look into dips bug (#32 )
- [x] Use an actual image instead of an emoji for the logo in the header
- [x] Sticky header

**Comment by jamesplease** [comment]
Resolved
